theme: jekyll-theme-hacker
github:
  #is_project_page: false
  repository_url: https://github.com/nkpro2000sr
author:
  name: Naveen S R
  email: "srnaveen2k@yahoo.com"
minima:
  social_links:
    linkedin: "https://www.linkedin.com/in/srnaveen2k"
    
